# Generated by Django 6.0 on 2025-12-25 09:34

import django.db.models.deletion
from archivebox import uuid_compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='bin_name',
            field=models.CharField(db_index=True, help_text='Binary executable name (e.g., wget, yt-dlp, chromium)', max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='bin_providers',
            field=models.CharField(default='*', help_text='Comma-separated list of allowed providers: apt,brew,pip,npm,gem,nix,custom or * for any', max_length=127),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON map of env var config to use during install'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='custom_cmds',
            field=models.JSONField(blank=True, default=dict, help_text="JSON map of provider -> custom install command (e.g., {'apt': 'apt install -y wget'})"),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='id',
            field=models.UUIDField(default=uuid_compat.uuid7, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='installedbinary',
            name='dependency',
            field=models.ForeignKey(blank=True, help_text='The Dependency this binary satisfies', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installedbinary_set', to='machine.dependency'),
        ),
        migrations.AlterField(
            model_name='installedbinary',
            name='id',
            field=models.UUIDField(default=uuid_compat.uuid7, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Machine-specific config overrides (e.g., resolved binary paths like WGET_BINARY)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='id',
            field=models.UUIDField(default=uuid_compat.uuid7, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='networkinterface',
            name='id',
            field=models.UUIDField(default=uuid_compat.uuid7, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
