# Generated by Django 5.1.1 on 2024-10-03 07:25
# Modified: Removed abid/charidfield - ABID system removed

import archivebox.base_models.models
import django.db.models.deletion
from django.db import migrations, models


def drop_installedbinary_abid_if_exist(apps, schema_editor):
    """Drop abid field from installedbinary if it exists."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        try:
            cursor.execute("PRAGMA table_info(machine_installedbinary)")
            columns = [row[1] for row in cursor.fetchall()]
            if 'abid' in columns:
                print("    Dropping machine_installedbinary.abid...")
                cursor.execute("ALTER TABLE machine_installedbinary DROP COLUMN abid")
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("machine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="stats",
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name="InstalledBinary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=None,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                # Removed: abid field - ABID system removed
                (
                    "created_at",
                    archivebox.base_models.models.AutoDateTimeField(
                        db_index=True, default=None
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default=None, max_length=63)),
                ("binprovider", models.CharField(default=None, max_length=31)),
                ("abspath", models.CharField(default=None, max_length=255)),
                ("version", models.CharField(default=None, max_length=32)),
                ("sha256", models.CharField(default=None, max_length=64)),
                (
                    "machine",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="machine.machine",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("machine", "name", "binprovider", "abspath", "version", "sha256")
                },
            },
        ),
        migrations.RunPython(drop_installedbinary_abid_if_exist, reverse_code=migrations.RunPython.noop),
    ]
