# Generated by Django 6.0 on 2025-12-28 05:12
# NOTE: This migration is intentionally empty but kept for dependency chain
# The Dependency model was removed in 0004, all operations stripped

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_rename_custom_cmds_to_overrides'),
    ]

    operations = [
        # All operations removed - Dependency model deleted in 0004
        # This is a stub migration for users upgrading from old dev versions
    ]
