# Generated by Django 6.0 on 2025-12-29 06:45

import django.db.models.deletion
import django.utils.timezone
from archivebox.uuid_compat import uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_drop_dependency_table'),
    ]

    operations = [
        # Update Django's state only - database already has correct schema
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='binary',
                    name='binproviders',
                    field=models.CharField(blank=True, default='env', help_text='Comma-separated list of allowed providers: apt,brew,pip,npm,env', max_length=127),
                ),
                migrations.AddField(
                    model_name='binary',
                    name='output_dir',
                    field=models.CharField(blank=True, default='', help_text='Directory where installation hook logs are stored', max_length=255),
                ),
                migrations.AddField(
                    model_name='binary',
                    name='overrides',
                    field=models.JSONField(blank=True, default=dict, help_text="Provider-specific overrides: {'apt': {'packages': ['pkg']}, ...}"),
                ),
                migrations.AddField(
                    model_name='binary',
                    name='retry_at',
                    field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, help_text='When to retry this binary installation', null=True),
                ),
                migrations.AddField(
                    model_name='binary',
                    name='status',
                    field=models.CharField(choices=[('queued', 'Queued'), ('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16),
                ),
                migrations.AlterField(
                    model_name='binary',
                    name='abspath',
                    field=models.CharField(blank=True, default='', max_length=255),
                ),
                migrations.AlterField(
                    model_name='binary',
                    name='binprovider',
                    field=models.CharField(blank=True, default='', help_text='Provider that successfully installed this binary', max_length=31),
                ),
                migrations.AlterField(
                    model_name='binary',
                    name='id',
                    field=models.UUIDField(default=uuid7, editable=False, primary_key=True, serialize=False, unique=True),
                ),
                migrations.AlterField(
                    model_name='binary',
                    name='machine',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine'),
                ),
                migrations.AlterField(
                    model_name='binary',
                    name='name',
                    field=models.CharField(blank=True, db_index=True, default='', max_length=63),
                ),
                migrations.AlterField(
                    model_name='binary',
                    name='sha256',
                    field=models.CharField(blank=True, default='', max_length=64),
                ),
                migrations.AlterField(
                    model_name='binary',
                    name='version',
                    field=models.CharField(blank=True, default='', max_length=32),
                ),
                migrations.AlterField(
                    model_name='machine',
                    name='config',
                    field=models.JSONField(blank=True, default=dict, help_text='Machine-specific config overrides (e.g., resolved binary paths like WGET_BINARY)', null=True),
                ),
                migrations.AlterField(
                    model_name='machine',
                    name='id',
                    field=models.UUIDField(default=uuid7, editable=False, primary_key=True, serialize=False, unique=True),
                ),
                migrations.AlterField(
                    model_name='machine',
                    name='stats',
                    field=models.JSONField(blank=True, default=dict, null=True),
                ),
                migrations.AlterField(
                    model_name='networkinterface',
                    name='id',
                    field=models.UUIDField(default=uuid7, editable=False, primary_key=True, serialize=False, unique=True),
                ),
            ],
            database_operations=[
                # No database changes - schema already correct from previous migrations
            ],
        ),
    ]
