# Generated by Django 6.0 on 2026-01-05 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0010_alter_process_process_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binary',
            name='output_dir',
        ),
    ]
