# Generated by Django 6.0.5 on 2026-05-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machine", "0012_add_machine_config_if_missing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="config",
            field=models.JSONField(blank=True, default=dict, help_text="Machine-specific config overrides.", null=True),
        ),
    ]
