# Generated by Django 6.0.5 on 2026-05-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machine", "0013_alter_machine_config"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="process",
            index=models.Index(fields=["pid", "started_at"], name="machine_pro_pid_6eec8b_idx"),
        ),
        migrations.AddIndex(
            model_name="process",
            index=models.Index(fields=["process_type", "worker_type", "pwd", "started_at"], name="machine_pro_process_b0411b_idx"),
        ),
    ]
