# Generated by ArchiveBox on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machine", "0017_shorten_process_progress_index_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="process_type",
            field=models.CharField(
                choices=[
                    ("supervisord", "Supervisord"),
                    ("orchestrator", "Orchestrator"),
                    ("server", "Server"),
                    ("update", "Update"),
                    ("add", "Add"),
                    ("search", "Search"),
                    ("worker", "Worker"),
                    ("cli", "CLI"),
                    ("hook", "Hook"),
                    ("binary", "Binary"),
                ],
                db_index=True,
                default="cli",
                help_text="Type of process (cli, worker, orchestrator, binary, supervisord)",
                max_length=16,
            ),
        ),
    ]
