# Generated by Django 6.0.6 on 2026-06-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("machine", "0020_repair_process_binary_iface_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkinterface",
            name="city",
            field=models.CharField(default="", max_length=63),
        ),
        migrations.AlterField(
            model_name="networkinterface",
            name="country",
            field=models.CharField(default="", max_length=63),
        ),
        migrations.AlterField(
            model_name="networkinterface",
            name="hostname",
            field=models.CharField(default="", max_length=63),
        ),
        migrations.AlterField(
            model_name="networkinterface",
            name="iface",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="networkinterface",
            name="isp",
            field=models.CharField(default="", max_length=63),
        ),
        migrations.AlterField(
            model_name="networkinterface",
            name="region",
            field=models.CharField(default="", max_length=63),
        ),
    ]
