# Generated by Django 6.0.6 on 2026-06-21 09:23

from django.db import migrations, models
from django.db.models import Count


def dedupe_network_interfaces_without_mac(apps, schema_editor):
    NetworkInterface = apps.get_model("machine", "NetworkInterface")
    Process = apps.get_model("machine", "Process")
    duplicate_groups = (
        NetworkInterface.objects.values(
            "machine_id",
            "ip_public",
            "ip_local",
            "dns_server",
        )
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )
    for group in duplicate_groups.iterator(chunk_size=100):
        lookup = {
            "machine_id": group["machine_id"],
            "ip_public": group["ip_public"],
            "ip_local": group["ip_local"],
            "dns_server": group["dns_server"],
        }
        keep = NetworkInterface.objects.filter(**lookup).order_by("-modified_at", "-created_at").first()
        if keep is None:
            continue
        duplicates = NetworkInterface.objects.filter(**lookup).exclude(id=keep.id)
        duplicate_ids = list(duplicates.values_list("id", flat=True))
        if not duplicate_ids:
            continue
        Process.objects.filter(iface_id__in=duplicate_ids).update(iface_id=keep.id)
        duplicates.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("machine", "0021_networkinterface_blank_defaults"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="networkinterface",
            name="unique_network_interface_identity",
        ),
        migrations.RunPython(dedupe_network_interfaces_without_mac, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="networkinterface",
            unique_together={("machine", "ip_public", "ip_local", "dns_server")},
        ),
        migrations.AddConstraint(
            model_name="networkinterface",
            constraint=models.UniqueConstraint(
                fields=("machine", "ip_public", "ip_local", "dns_server"),
                name="unique_network_interface_identity",
            ),
        ),
    ]
