# Generated by Django 5.1.2 on 2025-12-29 10:16

import abid_utils.models
import charidfield.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import statemachine.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0075_archiveresult_retry_at'),
        ('seeds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_uses_failed', models.PositiveIntegerField(default=0)),
                ('num_uses_succeeded', models.PositiveIntegerField(default=0)),
                ('schedule', models.CharField(max_length=64)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', abid_utils.models.AutoDateTimeField(db_index=True, default=None)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Crawl',
            fields=[
                ('num_uses_failed', models.PositiveIntegerField(default=0)),
                ('num_uses_succeeded', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('abid', charidfield.fields.CharIDField(blank=True, db_index=True, default=None, help_text='ABID-format identifier for this entity (e.g. snp_01BJQMF54D093DXEAWZ6JYRPAQ)', max_length=30, null=True, prefix='crl_', unique=True)),
                ('created_at', abid_utils.models.AutoDateTimeField(db_index=True, default=None)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('started', 'Started'), ('sealed', 'Sealed')], db_index=True, default='queued', max_length=15)),
                ('retry_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('max_depth', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('tags_str', models.CharField(blank=True, default='', max_length=1024)),
                ('persona', models.CharField(blank=True, default='auto', max_length=32)),
                ('config', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='crawl_set', to=settings.AUTH_USER_MODEL)),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crawl_set', to='seeds.seed')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawls.crawlschedule')),
            ],
            options={
                'verbose_name': 'Crawl',
                'verbose_name_plural': 'Crawls',
            },
            bases=(models.Model, statemachine.mixins.MachineMixin),
        ),
        migrations.CreateModel(
            name='Outlink',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('src', models.URLField()),
                ('dst', models.URLField()),
                ('crawl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlink_set', to='crawls.crawl')),
                ('via', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlink_set', to='core.archiveresult')),
            ],
            options={
                'unique_together': {('src', 'dst', 'via')},
            },
        ),
    ]
