# Generated by Django 6.0 on 2025-12-25 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Outlink',
        ),
    ]
