# Generated by Django 6.0 on 2025-12-27 01:40

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0002_drop_seed_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawl',
            name='output_dir',
            field=models.FilePathField(blank=True, default='', path=pathlib.PurePosixPath('/private/tmp/test_archivebox_migrations/archive')),
        ),
    ]
