# Generated by Django 6.0 on 2025-12-28 05:12

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0003_alter_crawl_output_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawl',
            name='output_dir',
            field=models.FilePathField(blank=True, default='', path=pathlib.PurePosixPath('/private/tmp/archivebox-makemigrations/archive')),
        ),
    ]
