# Generated by Django 6.0 on 2026-03-23 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawls", "0004_remove_crawl_output_dir"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawl",
            name="max_size",
            field=models.BigIntegerField(
                default=0,
                help_text="Maximum total archived output size in bytes for this crawl (0 = unlimited).",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="crawl",
            name="max_urls",
            field=models.IntegerField(
                default=0,
                help_text="Maximum number of URLs to snapshot for this crawl (0 = unlimited).",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
