# Generated by Django 6.0.5 on 2026-05-24 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawls", "0005_add_crawl_limits"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="crawl",
            index=models.Index(fields=["-created_at", "-retry_at"], name="crawl_admin_order_idx"),
        ),
    ]
