# Generated by Django 6.0 on 2025-12-29 06:45

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0005_drop_seed_id_column'),
    ]

    operations = [
        # Update Django's state only - database already correct
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='crawl',
                    name='config',
                    field=models.JSONField(blank=True, default=dict, null=True),
                ),
                migrations.AlterField(
                    model_name='crawl',
                    name='output_dir',
                    field=models.FilePathField(blank=True, default='', path=pathlib.PurePosixPath('/Users/squash/Local/Code/archiveboxes/archivebox-nue/data/archive')),
                ),
                migrations.DeleteModel(
                    name='Seed',
                ),
            ],
            database_operations=[
                # No database changes - Seed table already dropped in 0005
            ],
        ),
    ]
