# Generated by Django 6.0.5 on 2026-05-24 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawls", "0006_crawl_crawl_admin_order_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="crawl",
            name="crawl_admin_order_idx",
        ),
        migrations.AddIndex(
            model_name="crawl",
            index=models.Index(fields=["-created_at", "-retry_at", "-id"], name="crawl_admin_order_idx"),
        ),
    ]
