# Generated by Django 6.0 on 2026-05-24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawls", "0007_remove_crawl_crawl_admin_order_idx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="crawl",
            old_name="max_size",
            new_name="crawl_max_size",
        ),
        migrations.AddField(
            model_name="crawl",
            name="snapshot_max_size",
            field=models.BigIntegerField(
                default=0,
                help_text="Maximum archived output size in bytes for each snapshot (0 = unlimited).",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="crawl",
            name="crawl_max_size",
            field=models.BigIntegerField(
                default=0,
                help_text="Maximum total archived output size in bytes for this crawl (0 = unlimited).",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
