# Generated by Django 6.0.5 on 2026-05-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawls", "0009_crawl_progress_status_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawl",
            name="delete_at",
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
