# Generated by hand on 2026-05-28

import django.db.models.deletion
from django.db import migrations, models


def clear_stale_persona_ids(apps, _schema_editor):
    Crawl = apps.get_model("crawls", "Crawl")
    Persona = apps.get_model("personas", "Persona")
    Crawl.objects.filter(persona_id__isnull=False).exclude(
        persona_id__in=Persona.objects.values_list("id", flat=True),
    ).update(persona_id=None)


class Migration(migrations.Migration):
    dependencies = [
        ("crawls", "0013_crawl_permissions"),
        ("personas", "0003_persona_permissions"),
    ]

    operations = [
        migrations.RunPython(clear_stale_persona_ids, migrations.RunPython.noop),
        migrations.RenameField(
            model_name="crawl",
            old_name="persona_id",
            new_name="persona",
        ),
        migrations.AlterField(
            model_name="crawl",
            name="persona",
            field=models.ForeignKey(
                blank=True,
                db_column="persona_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crawls",
                to="personas.persona",
            ),
        ),
    ]
