# Read the Docs config for https://docs.archivebox.io
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

submodules:
  include: all
  recursive: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    #nodejs: "20"     # not needed unless we need the full archivebox to run while building docs for some reason

sphinx:
  configuration: docs/conf.py

formats:
  - pdf
  - epub

# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - requirements: docs/requirements.txt
