# Example: Using ArchiveBox in your own project

FROM python:3.12-slim

WORKDIR /app

RUN pip install archivebox==0.8.5rc50
RUN archivebox install

RUN useradd -ms /bin/bash archivebox && chown -R archivebox /app











