# Generated by Django 5.1.2 on 2025-12-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0074_alter_snapshot_downloaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinglefileResult',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.archiveresult',),
        ),
    ]
