# Generated by Django 3.1.14 on 2024-01-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AptEnvironmentDependency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ENABLED', models.BooleanField(default=True)),
                ('BINARY', models.CharField(default='apt-get', max_length=255)),
                ('ARGS', models.CharField(default='-qq', max_length=255)),
            ],
            options={
                'verbose_name': 'Package Manager: apt',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArchiveBoxDependency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ENABLED', models.BooleanField(default=True, editable=False)),
                ('BINARY', models.CharField(default='archivebox', editable=False, max_length=255)),
                ('ARGS', models.CharField(default=[], editable=False, max_length=255)),
            ],
            options={
                'verbose_name': 'Internal Dependency: ArchiveBox Package',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BashEnvironmentDependency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ENABLED', models.BooleanField(default=True, editable=False)),
                ('BINARY', models.CharField(default='bash', max_length=255)),
                ('ARGS', models.CharField(default='-c', max_length=255)),
            ],
            options={
                'verbose_name': 'Shell Environment: bash',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrewEnvironmentDependency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ENABLED', models.BooleanField(default=True)),
                ('BINARY', models.CharField(default='brew', max_length=255)),
                ('ARGS', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Package Manager: brew',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoDependency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ENABLED', models.BooleanField(default=True, editable=False)),
                ('BINARY', models.CharField(default='django-admin.py', editable=False, max_length=255)),
                ('ARGS', models.CharField(default=[], editable=False, max_length=255)),
            ],
            options={
                'verbose_name': 'Internal Dependency: Django Package',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeJSEnvironmentDependency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ENABLED', models.BooleanField(default=True)),
                ('BINARY', models.CharField(default='node', max_length=255)),
                ('ARGS', models.CharField(default='-c', max_length=255)),
            ],
            options={
                'verbose_name': 'Shell Environment: NodeJS',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NPMEnvironmentDependency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ENABLED', models.BooleanField(default=True)),
                ('BINARY', models.CharField(default='node', max_length=255)),
                ('ARGS', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Package Manager: npm',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PipEnvironmentDependency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ENABLED', models.BooleanField(default=True)),
                ('BINARY', models.CharField(default='pip3', max_length=255)),
                ('ARGS', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Package Manager: pip',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PythonEnvironmentDependency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ENABLED', models.BooleanField(default=True, editable=False)),
                ('BINARY', models.CharField(default='python3', max_length=255)),
                ('ARGS', models.CharField(default='-c', max_length=255)),
            ],
            options={
                'verbose_name': 'Shell Environment: Python3',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SQLiteDependency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ENABLED', models.BooleanField(default=True, editable=False)),
                ('BINARY', models.CharField(default='sqlite3', editable=False, max_length=255)),
                ('ARGS', models.CharField(default=[], editable=False, max_length=255)),
            ],
            options={
                'verbose_name': 'Internal Dependency: SQLite3 Package',
                'abstract': False,
            },
        ),
    ]
