# Generated by Django 3.1.14 on 2024-01-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20240124_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bashenvironmentdependency',
            options={'verbose_name': 'Shell Environment: bash', 'verbose_name_plural': 'Shell Environments: bash'},
        ),
        migrations.AddField(
            model_name='bashenvironmentdependency',
            name='VERSION_CMD',
            field=models.CharField(default='{BINARY} --version', max_length=255),
        ),
    ]
