# Generated by Django 6.0 on 2026-01-05 01:09

from django.db import migrations, models

from archivebox.uuid_compat import uuid7


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.UUIDField(default=uuid7, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
