# Generated by Django 6.0.5 on 2026-05-28 07:25

import django.db.models.fields.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personas", "0002_alter_persona_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="permissions",
            field=models.GeneratedField(
                db_index=True,
                db_persist=True,
                expression=django.db.models.fields.json.KeyTextTransform("PERMISSIONS", "config"),
                output_field=models.CharField(max_length=16, null=True),
            ),
        ),
    ]
