[project]
name = "abx"
version = "0.1.0"
description = "The common shared interfaces for the ABX ArchiveBox plugin ecosystem."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pluggy>=1.5.0",
    "django>=5.1.1,<6.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
