# Generated by Django 6.1.2 on 2026-10-09 11:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import archivebox.uuid_compat


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("crawls", "0019_crawlschedule_config"),
        ("machine", "0023_repair_binary_field_indexes"),
        ("personas", "0004_hydrate_persona_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImporterSource",
            fields=[
                ("id", models.UUIDField(default=archivebox.uuid_compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=200)),
                ("plugin", models.CharField(max_length=100)),
                ("feed", models.CharField(max_length=100)),
                ("settings", models.JSONField(default=dict)),
                ("checkpoint", models.JSONField(default=dict)),
                ("account", models.JSONField(default=dict)),
                ("limit", models.PositiveIntegerField(default=100)),
                ("tags", models.CharField(blank=True, max_length=1024)),
                ("schedule", models.CharField(blank=True, max_length=64)),
                ("enabled", models.BooleanField(default=True)),
                ("next_run_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("persona", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="personas.persona")),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ImporterRun",
            fields=[
                ("id", models.UUIDField(default=archivebox.uuid_compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[("check", "Check access"), ("preview", "Preview"), ("import", "Import")],
                        default="import",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("needs_login", "Needs login"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("cancel_requested", models.BooleanField(default=False)),
                ("request", models.JSONField(default=dict)),
                ("items", models.JSONField(default=list)),
                ("result", models.JSONField(default=dict)),
                ("message", models.TextField(blank=True)),
                (
                    "crawl",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_runs",
                        to="crawls.crawl",
                    ),
                ),
                ("owner", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="machine.process")),
                (
                    "source",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="importers.importersource"),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["queued", "running"])),
                        fields=("source",),
                        name="importers_one_active_run",
                    ),
                ],
            },
        ),
    ]
