# Generated by Django 5.0.6 on 2024-05-18 01:16

import archivebox.plugantic.plugins
import django.core.serializers.json
import django_pydantic_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugantic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='schema',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=archivebox.plugantic.plugins.Plugin),
        ),
    ]
