# Generated by Django 5.0.6 on 2024-05-18 01:45

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugantic', '0005_customplugin_delete_plugin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customplugin',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, path=pathlib.PurePosixPath('/Volumes/NVME/Users/squash/Local/Code/archiveboxes/ArchiveBox/archivebox/plugins'), recursive=True),
        ),
    ]
