# Generated by Django 5.0.6 on 2024-05-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugantic', '0010_alter_customplugin_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customplugin',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, match='plugins/*', path='/Volumes/NVME/Users/squash/Local/Code/archiveboxes/ArchiveBox/data', recursive=True),
        ),
    ]
