# Generated by Django 5.0.6 on 2024-05-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugantic', '0012_alter_customplugin_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customplugin',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, default='/plugins/example_plugin', match='plugins/*', path='/Volumes/NVME/Users/squash/Local/Code/archiveboxes/ArchiveBox/data', recursive=True),
        ),
    ]
