# Generated by Django 5.0.6 on 2024-05-18 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugantic', '0015_alter_customplugin_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPlugin',
        ),
    ]
