# Generated by Django 5.1 on 2024-08-20 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import archivebox.base_models.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_outboundwebhook_uuid_apitoken_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='created_by',
            field=models.ForeignKey(default=archivebox.base_models.models.get_or_create_system_user_pk, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
