[project]
name = "abx-plugin-default-binproviders"
version = "2024.10.24"
description = "Default BinProviders for ABX (apt, brew, env)"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "abx>=0.1.0",
    "abx-pkg>=0.5.4",
    "abx-spec-abx-pkg>=0.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.entry-points.abx]
abx_plugin_default_binproviders = "abx_plugin_default_binproviders"
