# Generated by Django 3.1.14 on 2024-01-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveBoxDefaultDependency',
            fields=[
                ('ENABLED', models.BooleanField(default=True, editable=False)),
                ('BINARY', models.CharField(default='/bin/false', max_length=255)),
                ('ARGS', models.CharField(default='', max_length=255)),
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Dependency Configuration Defaults',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArchiveBoxDefaultExtractor',
            fields=[
                ('ENABLED', models.BooleanField(default=True)),
                ('CMD', models.CharField(default=['{DEPENDENCY.BINARY}', '{ARGS}', '{url}'], max_length=255)),
                ('ARGS', models.CharField(default=['--timeout={TIMEOUT}'], max_length=255)),
                ('TIMEOUT', models.CharField(default='{TIMEOUT}', max_length=255)),
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Extractor Configuration Defaults',
                'abstract': False,
            },
        ),
    ]
