# Generated by Django 3.0.8 on 2020-11-03 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201012_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(default='', max_length=500)),
                ('pwd', models.CharField(default='', max_length=200)),
                ('cmd_version', models.CharField(default='', max_length=20)),
                ('output', models.CharField(default='', max_length=500)),
                ('start_ts', models.DateTimeField()),
                ('end_ts', models.DateTimeField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Snapshot')),
            ],
        ),
    ]
