# Generated by Django 3.0.8 on 2020-10-30 17:05

from django.db import migrations, models, transaction
import django.db.models.deletion
import uuid

def migrate_snapshots(apps, schema_editor):
    Snapshot = apps.get_model('core', 'Snapshot')
    Link = apps.get_model('core', 'Link')

    with transaction.atomic():
        for snapshot in Snapshot.objects.all():
            link = Link(
                url=snapshot.url,
                added=snapshot.added,
            )
            link.save()

            for tag in snapshot.tags.all():
                link.tags.add(tag)

            snapshot.link = link
            snapshot.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201012_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tags', models.ManyToManyField(to='core.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='snapshot',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Link'),
        ),
        migrations.RunPython(migrate_snapshots),
        migrations.RemoveField(
            model_name='snapshot',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='url',
        ),
    ]
