# Generated by Django 3.1.3 on 2020-12-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_archiveresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveresult',
            name='extractor',
            field=models.CharField(choices=['title', 'wget'], max_length=32),
        ),
    ]
