# Generated by Django 3.1.3 on 2021-02-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210216_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveresult',
            name='cmd_version',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='output',
            field=models.CharField(max_length=1024),
        ),
    ]
