# Generated by Django 3.1.14 on 2022-01-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210410_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='url',
            field=models.URLField(db_index=True, max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=2048, null=True),
        ),
    ]
