# Generated by Django 3.1.14 on 2023-03-20 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20220914_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='added',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
