# Generated by Django 3.1.14 on 2022-01-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20220128_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=2048, null=True),
        ),
    ]
