# Generated by Django 4.2.13 on 2024-06-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_auto_20231023_2008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archiveresult",
            name="extractor",
            field=models.CharField(
                choices=[
                    ("favicon", "favicon"),
                    ("headers", "headers"),
                    ("singlefile", "singlefile"),
                    ("pdf", "pdf"),
                    ("screenshot", "screenshot"),
                    ("dom", "dom"),
                    ("wget", "wget"),
                    ("title", "title"),
                    ("readability", "readability"),
                    ("mercury", "mercury"),
                    ("htmltotext", "htmltotext"),
                    ("git", "git"),
                    ("media", "media"),
                    ("papers_dl", "papers_dl"),
                    ("archive_org", "archive_org"),
                ],
                max_length=32,
            ),
        ),
    ]
