# Generated by Django 5.0.6 on 2024-12-25
# Adds crawl FK and iface FK after crawls and machine apps are created

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_new_schema'),
        ('crawls', '0001_initial'),
        ('machine', '0001_squashed'),
    ]

    operations = [
        # Add crawl FK to Snapshot
        migrations.AddField(
            model_name='snapshot',
            name='crawl',
            field=models.ForeignKey(
                default=None, null=True, blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='snapshot_set',
                to='crawls.crawl',
                db_index=True,
            ),
        ),

        # Add network interface FK to ArchiveResult
        migrations.AddField(
            model_name='archiveresult',
            name='iface',
            field=models.ForeignKey(
                null=True, blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='machine.networkinterface',
            ),
        ),
    ]
