# Generated by hand on 2025-12-29
# Increases Snapshot.url max_length from 200 to 1600 characters

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_assign_default_crawl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='url',
            field=models.URLField(max_length=1600, db_index=True),
        ),
    ]
