# Generated by Django 5.0.6 on 2024-06-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_archiveresult_extractor'),
        ('core', '0026_archiveresult_created_archiveresult_created_by_and_more'),
    ]

    operations = [
    ]
