# Generated by Django 6.0 on 2025-12-31 09:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from archivebox.uuid_compat import uuid7


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_final_field_adjustments'),
        ('crawls', '0002_upgrade_to_0_9_0'),
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveresult',
            name='hook_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Full filename of the hook that executed (e.g., on_Snapshot__50_wget.py)', max_length=255),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='output_files',
            field=models.JSONField(default=dict, help_text='Dict of {relative_path: {metadata}}'),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='output_json',
            field=models.JSONField(blank=True, default=None, help_text='Structured metadata (headers, redirects, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='output_mimetypes',
            field=models.CharField(blank=True, default='', help_text='CSV of mimetypes sorted by size', max_length=512),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='output_size',
            field=models.BigIntegerField(default=0, help_text='Total bytes of all output files'),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='output_str',
            field=models.TextField(blank=True, default='', help_text='Human-readable output summary'),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='plugin',
            field=models.CharField(db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='process',
            field=models.OneToOneField(help_text='Process execution details for this archive result', on_delete=django.db.models.deletion.PROTECT, related_name='archiveresult', to='machine.process'),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='retry_at',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('started', 'Started'), ('backoff', 'Waiting to retry'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='queued', max_length=15),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid7, null=True),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='crawl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_set', to='crawls.crawl'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='current_step',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Current hook step being executed (0-9). Used for sequential hook execution.'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='depth',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='id',
            field=models.UUIDField(default=uuid7, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='snapshottag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
