# Generated by Django 5.0.6 on 2024-08-18 04:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_update_snapshot_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveresult',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
