# Generated by Django 6.0 on 2026-01-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_copy_archiveresult_to_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='fs_version',
            field=models.CharField(default='0.9.0', help_text='Filesystem version of this snapshot (e.g., "0.7.0", "0.8.0", "0.9.0"). Used to trigger lazy migration on save().', max_length=10),
        ),
    ]
