# Generated by Django for hook architecture support
# Phase 1: Migrate existing 'output' field to new split fields

from django.db import migrations
import json


def migrate_output_field(apps, schema_editor):
    """
    Migrate existing 'output' field to new split fields.

    Logic:
    - If output contains JSON {...}, move to output_json
    - Otherwise, move to output_str
    """
    ArchiveResult = apps.get_model('core', 'ArchiveResult')

    for ar in ArchiveResult.objects.all().iterator():
        old_output = ar.output or ''

        # Case 1: JSON output
        if old_output.strip().startswith('{'):
            try:
                parsed = json.loads(old_output)
                ar.output_json = parsed
                ar.output_str = ''
            except json.JSONDecodeError:
                # Not valid JSON, treat as string
                ar.output_str = old_output

        # Case 2: File path or plain string
        else:
            ar.output_str = old_output

        ar.save(update_fields=['output_str', 'output_json'])


def reverse_migrate(apps, schema_editor):
    """Reverse migration - copy output_str back to output."""
    ArchiveResult = apps.get_model('core', 'ArchiveResult')

    for ar in ArchiveResult.objects.all().iterator():
        if ar.output_json:
            ar.output = json.dumps(ar.output_json)
        else:
            ar.output = ar.output_str or ''
        ar.save(update_fields=['output'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_archiveresult_hook_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_output_field, reverse_migrate),

        # Now safe to remove old 'output' field
        migrations.RemoveField(
            model_name='archiveresult',
            name='output',
        ),
    ]
