# Generated by Django for hook architecture support
# Phase 1: Migrate existing 'output' field to new split fields

from django.db import migrations
import json


def migrate_output_field(apps, schema_editor):
    """
    Migrate existing 'output' field to new split fields.

    Logic:
    - If output contains JSON {...}, move to output_json
    - Otherwise, move to output_str

    Use raw SQL to avoid CHECK constraint issues during migration.
    """
    # Use raw SQL to migrate data without triggering CHECK constraints
    with schema_editor.connection.cursor() as cursor:
        # Get all archive results
        cursor.execute("""
            SELECT id, output FROM core_archiveresult
        """)

        for row in cursor.fetchall():
            ar_id, old_output = row
            old_output = old_output or ''

            # Case 1: JSON output
            if old_output.strip().startswith('{'):
                try:
                    # Validate it's actual JSON
                    parsed = json.loads(old_output)
                    # Update with JSON - cast to JSON to satisfy CHECK constraint
                    json_str = json.dumps(parsed)
                    cursor.execute("""
                        UPDATE core_archiveresult
                        SET output_str = '', output_json = json(?)
                        WHERE id = ?
                    """, (json_str, ar_id))
                except json.JSONDecodeError:
                    # Not valid JSON, treat as string
                    cursor.execute("""
                        UPDATE core_archiveresult
                        SET output_str = ?, output_json = NULL
                        WHERE id = ?
                    """, (old_output, ar_id))
            # Case 2: File path or plain string
            else:
                cursor.execute("""
                    UPDATE core_archiveresult
                    SET output_str = ?, output_json = NULL
                    WHERE id = ?
                """, (old_output, ar_id))


def reverse_migrate(apps, schema_editor):
    """Reverse migration - copy output_str back to output."""
    ArchiveResult = apps.get_model('core', 'ArchiveResult')

    for ar in ArchiveResult.objects.all().iterator():
        if ar.output_json:
            ar.output = json.dumps(ar.output_json)
        else:
            ar.output = ar.output_str or ''
        ar.save(update_fields=['output'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_archiveresult_hook_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_output_field, reverse_migrate),

        # Now safe to remove old 'output' field
        migrations.RemoveField(
            model_name='archiveresult',
            name='output',
        ),
    ]
