# Generated by Django 6.0 on 2025-12-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_migrate_output_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='parent_snapshot',
            field=models.ForeignKey(
                blank=True,
                db_index=True,
                help_text='Parent snapshot that discovered this URL (for recursive crawling)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='child_snapshots',
                to='core.snapshot'
            ),
        ),
    ]
