# Generated by Django 6.0 on 2025-12-28 05:12

import django.db.models.deletion
from archivebox import uuid_compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_snapshot_parent_snapshot'),
        ('crawls', '0004_alter_crawl_output_dir'),
        ('machine', '0003_alter_dependency_id_alter_installedbinary_dependency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveresult',
            name='binary',
            field=models.ForeignKey(blank=True, help_text='Primary binary used by this hook', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archiveresults', to='machine.binary'),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='output_files',
            field=models.JSONField(default=dict, help_text='Dict of {relative_path: {metadata}}'),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='output_json',
            field=models.JSONField(blank=True, default=None, help_text='Structured metadata (headers, redirects, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='output_mimetypes',
            field=models.CharField(blank=True, default='', help_text='CSV of mimetypes sorted by size', max_length=512),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='output_size',
            field=models.BigIntegerField(default=0, help_text='Total bytes of all output files'),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='output_str',
            field=models.TextField(blank=True, default='', help_text='Human-readable output summary'),
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid_compat.uuid7, null=True),
        ),
        migrations.AddConstraint(
            model_name='snapshot',
            constraint=models.UniqueConstraint(fields=('timestamp',), name='unique_timestamp'),
        ),
    ]
