# Generated by Django 5.0.6 on 2024-08-18 05:20

import core.models
import random
from django.db import migrations, models


def rand_int_id():
    return random.getrandbits(32)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_archiveresult_id_alter_archiveresult_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveresult',
            name='id',
            field=models.BigIntegerField(default=rand_int_id, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
