# Generated by Django 6.0 on 2025-12-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_archiveresult_binary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archiveresult',
            old_name='extractor',
            new_name='plugin',
        ),
        migrations.AddField(
            model_name='archiveresult',
            name='hook_name',
            field=models.CharField(
                blank=True,
                default='',
                max_length=255,
                db_index=True,
                help_text='Full filename of the hook that executed (e.g., on_Snapshot__50_wget.py)'
            ),
        ),
    ]
