# Generated by Django 6.0 on 2025-12-28
# Add Snapshot.current_step field for hook step-based execution

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_rename_extractor_add_hook_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='current_step',
            field=models.PositiveSmallIntegerField(
                default=0,
                db_index=True,
                help_text='Current hook step being executed (0-9). Used for sequential hook execution.'
            ),
        ),
    ]
