# Generated by Django 6.0.5 on 2026-05-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_remove_tag_slug"),
        ("machine", "0013_alter_machine_config"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="archiveresult",
            index=models.Index(fields=["-start_ts", "-id"], name="archiveresult_start_idx"),
        ),
    ]
