# Generated by Django 6.0.5 on 2026-05-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_archiveresult_archiveresult_start_idx"),
        ("crawls", "0007_remove_crawl_crawl_admin_order_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="snapshot",
            index=models.Index(fields=["-bookmarked_at", "-created_at"], name="snapshot_public_order_idx"),
        ),
    ]
