# Generated by Django 6.0 on 2025-12-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_archiveresult_created_by'),
    ]

    operations = [
        # Update Django's state only - database columns remain for backwards compat
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='archiveresult',
                    name='output_dir',
                ),
                migrations.RemoveField(
                    model_name='snapshot',
                    name='output_dir',
                ),
                migrations.AlterField(
                    model_name='archiveresult',
                    name='config',
                    field=models.JSONField(blank=True, default=dict, null=True),
                ),
                migrations.AlterField(
                    model_name='snapshot',
                    name='config',
                    field=models.JSONField(blank=True, default=dict, null=True),
                ),
                migrations.AlterField(
                    model_name='snapshot',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='snapshot_set', through='core.SnapshotTag', through_fields=('snapshot', 'tag'), to='core.tag'),
                ),
            ],
            database_operations=[
                # No database changes - columns remain in place to avoid table rebuilds
            ],
        ),
    ]
