# Generated by ArchiveBox on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_alter_snapshot_url_max_length"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="snapshot",
            index=models.Index(fields=["crawl", "status", "modified_at"], name="snapshot_progress_idx"),
        ),
    ]
