# Generated by Django 6.0.5 on 2026-05-27 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_snapshot_progress_idx"),
        ("machine", "0015_process_progress_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archiveresult",
            name="process",
            field=models.OneToOneField(
                blank=True,
                help_text="Process execution details for this archive result",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archiveresult",
                to="machine.process",
            ),
        ),
    ]
