# Generated by Django 6.0.5 on 2026-05-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_alter_archiveresult_process"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveresult",
            name="delete_at",
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="snapshot",
            name="delete_at",
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
