# Generated by Django 6.0.5 on 2026-05-28 08:22

from django.db import migrations, models
from django.db.models import Sum


def backfill_snapshot_output_size(apps, schema_editor):
    Snapshot = apps.get_model("core", "Snapshot")
    ArchiveResult = apps.get_model("core", "ArchiveResult")
    batch = []
    rows = ArchiveResult.objects.values("snapshot_id").annotate(total_size=Sum("output_size")).order_by()
    for row in rows.iterator(chunk_size=2000):
        batch.append(Snapshot(id=row["snapshot_id"], output_size=row["total_size"] or 0))
        if len(batch) >= 2000:
            Snapshot.objects.bulk_update(batch, ["output_size"], batch_size=2000)
            batch = []
    if batch:
        Snapshot.objects.bulk_update(batch, ["output_size"], batch_size=2000)


def clear_snapshot_output_size(apps, schema_editor):
    Snapshot = apps.get_model("core", "Snapshot")
    Snapshot.objects.update(output_size=0)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_snapshot_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="output_size",
            field=models.BigIntegerField(
                db_index=True,
                default=0,
                editable=False,
                help_text="Total bytes of all ArchiveResult output files",
            ),
        ),
        migrations.RunPython(backfill_snapshot_output_size, clear_snapshot_output_size),
    ]
