# Generated by Django 6.0.5 on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_snapshot_output_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveresult",
            name="retry_at",
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
