# Generated by Django 6.0.6 on 2026-06-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_remove_archiveresult_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snapshot",
            name="url",
            field=models.TextField(db_index=True),
        ),
    ]
