# Generated by Django 6.1 on 2026-08-30 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_unique_archiveresult_per_snapshot_plugin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="archiveresult",
            options={"verbose_name": "Archive Result", "verbose_name_plural": "Archive Results"},
        ),
    ]
