# Generated by Django 6.1 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_alter_archiveresult_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snapshot",
            name="current_step",
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="fs_version",
            field=models.CharField(
                db_index=True,
                default="0.9.0",
                help_text='Filesystem version of this snapshot (e.g., "0.7.0", "0.8.0", "0.9.4").',
                max_length=10,
            ),
        ),
    ]
