# Generated by Django 6.1 on 2026-09-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_repair_legacy_retry_timestamps"),
        ("crawls", "0019_crawlschedule_config"),
        ("machine", "0022_networkinterface_identity_without_mac"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="archiveresult",
            index=models.Index(fields=["status", "plugin", "snapshot"], name="archiveresult_progress_idx"),
        ),
        migrations.AddIndex(
            model_name="snapshot",
            index=models.Index(fields=["crawl", "status", "downloaded_at", "output_size"], name="snapshot_progress_totals_idx"),
        ),
    ]
