# Generated by Django 6.1 on 2026-09-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_repair_migrated_process_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snapshot",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("started", "Started"),
                    ("paused", "Paused"),
                    ("sealed", "Sealed"),
                    ("deleting", "Deleting"),
                ],
                db_index=True,
                default="queued",
                max_length=15,
            ),
        ),
    ]
