# Generated by Django 5.0.6 on 2024-08-20 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_snapshottag_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshottag',
            name='old_tag',
        ),
    ]
