# Generated by Django 5.0.6 on 2024-08-20 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_snapshottag_tag_alter_tag_id_alter_tag_old_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshottag',
            name='tag',
            field=models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='core.tag'),
        ),
    ]
