# Generated by Django 5.1.2 on 2025-12-29 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_alter_snapshot_downloaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveresult',
            name='retry_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
