name: Run linters

on:
  workflow_dispatch:
  push:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          architecture: x64

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies with uv
        run: uv sync --all-extras --all-groups --no-sources --no-cache

      - name: Run prek
        run: uv run prek run --all-files
